# Generated by Django 2.2.15 on 2021-04-26 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0002_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
