# Generated by Django 2.2.15 on 2021-04-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0003_matchup_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='date_created',
            new_name='dateCreated',
        ),
    ]
