# Generated by Django 2.2.15 on 2022-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0006_matchup_p1aligulacodds'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='KellyValue',
            field=models.IntegerField(default=0),
        ),
    ]
