# Generated by Django 2.2.15 on 2022-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0008_auto_20220318_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='kellyValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='p1AligulacOdds',
            field=models.FloatField(default=0),
        ),
    ]
