# Generated by Django 2.2.15 on 2022-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0009_auto_20220318_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='best_of',
            new_name='bestOf',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
