# Generated by Django 2.2.15 on 2022-03-31 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0010_auto_20220330_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='dateCreated',
        ),
        migrations.AddField(
            model_name='matchup',
            name='matchupDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
