# Generated by Django 2.2.15 on 2022-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0011_auto_20220331_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='p1Odds',
            field=models.FloatField(default=0),
        ),
    ]
