# Generated by Django 2.2.15 on 2022-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0012_auto_20220405_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aligulac_id',
            field=models.FloatField(default=0),
        ),
    ]
