# Generated by Django 2.2.15 on 2022-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0013_player_aligulac_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aligulac_id',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
