# Generated by Django 2.2.15 on 2022-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0014_auto_20220728_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
