# Generated by Django 2.2.15 on 2022-07-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scodds', '0016_player_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
    ]
